/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule App_viewer.graphql
 * @generated SignedSource<<3ba1521d50437d945123d5f37cdab340>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type App_viewer = {|
  +user: ?{| |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "App_viewer",
  "selections": [
    {
      "kind": "LinkedField",
      "alias": null,
      "args": null,
      "concreteType": "UserNode",
      "name": "user",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "UserDropDown_user",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
