/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule UserDropDown_user.graphql
 * @generated SignedSource<<571da5a8f6e1ac61b2f47135890d310d>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type UserDropDown_user = {|
  +username: string;
  +email: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "UserDropDown_user",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "username",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "email",
      "storageKey": null
    }
  ],
  "type": "UserNode"
};

module.exports = fragment;
