# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('text',
                 models.CharField(
                     max_length=100)),
            ],
            options={
                'verbose_name': 'todo',
            },
        ),
    ]
