/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PollsDetailViewerRefetchQuery.graphql
 * @generated SignedSource<<ae5dcf4b812bd4de482fba58fc690aa7>>
 * @relayHash 44e1e567e3a085bc7f7065a29c069c96
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query PollsDetailViewerRefetchQuery(
  $id: ID!
) {
  viewer {
    ...PollsDetail_viewer_1Bmzm5
    id
  }
}

fragment PollsDetail_viewer_1Bmzm5 on Viewer {
  id
  question(id: $id) {
    questionText
    hasViewerVoted
    ...PollsVote_question
    ...PollsResults_question
    id
  }
}

fragment PollsVote_question on Question {
  id
  questionText
  choiceSet(first: 10) {
    ...PollChoices_choiceSet
  }
}

fragment PollsResults_question on Question {
  id
  questionText
  choiceSet(first: 10) {
    edges {
      node {
        id
        choiceText
        voteCount
      }
    }
  }
}

fragment PollChoices_choiceSet on ChoiceConnection {
  edges {
    node {
      id
      choiceText
      voteCount
    }
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "PollsDetailViewerRefetchQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "PollsDetail_viewer",
            "args": [
              {
                "kind": "Variable",
                "name": "id",
                "variableName": "id",
                "type": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "PollsDetailViewerRefetchQuery",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "id",
        "type": "ID!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "PollsDetailViewerRefetchQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Variable",
                "name": "id",
                "variableName": "id",
                "type": "ID!"
              }
            ],
            "concreteType": "Question",
            "name": "question",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "questionText",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "hasViewerVoted",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              },
              {
                "kind": "LinkedField",
                "alias": null,
                "args": [
                  {
                    "kind": "Literal",
                    "name": "first",
                    "value": 10,
                    "type": "Int"
                  }
                ],
                "concreteType": "ChoiceConnection",
                "name": "choiceSet",
                "plural": false,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "ChoiceEdge",
                    "name": "edges",
                    "plural": true,
                    "selections": [
                      {
                        "kind": "LinkedField",
                        "alias": null,
                        "args": null,
                        "concreteType": "Choice",
                        "name": "node",
                        "plural": false,
                        "selections": [
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "id",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "choiceText",
                            "storageKey": null
                          },
                          {
                            "kind": "ScalarField",
                            "alias": null,
                            "args": null,
                            "name": "voteCount",
                            "storageKey": null
                          }
                        ],
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": "choiceSet{\"first\":10}"
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query PollsDetailViewerRefetchQuery(\n  $id: ID!\n) {\n  viewer {\n    ...PollsDetail_viewer_1Bmzm5\n    id\n  }\n}\n\nfragment PollsDetail_viewer_1Bmzm5 on Viewer {\n  id\n  question(id: $id) {\n    questionText\n    hasViewerVoted\n    ...PollsVote_question\n    ...PollsResults_question\n    id\n  }\n}\n\nfragment PollsVote_question on Question {\n  id\n  questionText\n  choiceSet(first: 10) {\n    ...PollChoices_choiceSet\n  }\n}\n\nfragment PollsResults_question on Question {\n  id\n  questionText\n  choiceSet(first: 10) {\n    edges {\n      node {\n        id\n        choiceText\n        voteCount\n      }\n    }\n  }\n}\n\nfragment PollChoices_choiceSet on ChoiceConnection {\n  edges {\n    node {\n      id\n      choiceText\n      voteCount\n    }\n  }\n}\n"
};

module.exports = batch;
