/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PollsVote_question.graphql
 * @generated SignedSource<<1cf00009b8a8d0805c7fc660edd0dc7e>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PollsVote_question = {|
  +id: string;
  +questionText: string;
  +choiceSet: ?{| |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "PollsVote_question",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "questionText",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Literal",
          "name": "first",
          "value": 10,
          "type": "Int"
        }
      ],
      "concreteType": "ChoiceConnection",
      "name": "choiceSet",
      "plural": false,
      "selections": [
        {
          "kind": "FragmentSpread",
          "name": "PollChoices_choiceSet",
          "args": null
        }
      ],
      "storageKey": "choiceSet{\"first\":10}"
    }
  ],
  "type": "Question"
};

module.exports = fragment;
