/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule PollsDetail_viewer.graphql
 * @generated SignedSource<<7e9cffbc47407b5da23dbe65a6f37ee9>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type PollsDetail_viewer = {|
  +id: string;
  +question: ?{|
    +questionText: string;
    +hasViewerVoted: ?boolean;
  |};
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [
    {
      "kind": "LocalArgument",
      "name": "id",
      "type": "ID!",
      "defaultValue": ""
    }
  ],
  "kind": "Fragment",
  "metadata": null,
  "name": "PollsDetail_viewer",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "LinkedField",
      "alias": null,
      "args": [
        {
          "kind": "Variable",
          "name": "id",
          "variableName": "id",
          "type": "ID!"
        }
      ],
      "concreteType": "Question",
      "name": "question",
      "plural": false,
      "selections": [
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "questionText",
          "storageKey": null
        },
        {
          "kind": "ScalarField",
          "alias": null,
          "args": null,
          "name": "hasViewerVoted",
          "storageKey": null
        },
        {
          "kind": "FragmentSpread",
          "name": "PollsVote_question",
          "args": null
        },
        {
          "kind": "FragmentSpread",
          "name": "PollsResults_question",
          "args": null
        }
      ],
      "storageKey": null
    }
  ],
  "type": "Viewer"
};

module.exports = fragment;
