/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Polls_question.graphql
 * @generated SignedSource<<d79e9dbe44819bc6cc15efdb2b01deb4>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Polls_question = {|
  +id: string;
  +questionText: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Polls_question",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "questionText",
      "storageKey": null
    }
  ],
  "type": "Question"
};

module.exports = fragment;
