# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todomodel',
            options={'verbose_name': 'todo'},
        ),
    ]
