/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule rootViewerQuery.graphql
 * @generated SignedSource<<ef19674e20d504140e37a4f9064869bc>>
 * @relayHash d09ebea6066dd9aa9646dcd1c330164e
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query rootViewerQuery {
  viewer {
    ...Account_viewer
    ...Polls_viewer
    user {
      ...UserDropDown_user
      id
    }
    id
  }
}

fragment Account_viewer on Viewer {
  id
}

fragment Polls_viewer on Viewer {
  questions(first: 10) {
    edges {
      node {
        id
        ...Polls_question
      }
    }
  }
}

fragment UserDropDown_user on UserNode {
  username
  email
}

fragment Polls_question on Question {
  id
  questionText
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "rootViewerQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": "viewer",
        "args": null,
        "concreteType": "Viewer",
        "name": "__viewer_viewer",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Account_viewer",
            "args": null
          },
          {
            "kind": "FragmentSpread",
            "name": "Polls_viewer",
            "args": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "UserNode",
            "name": "user",
            "plural": false,
            "selections": [
              {
                "kind": "FragmentSpread",
                "name": "UserDropDown_user",
                "args": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "rootViewerQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "rootViewerQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Viewer",
        "name": "viewer",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": [
              {
                "kind": "Literal",
                "name": "first",
                "value": 10,
                "type": "Int"
              }
            ],
            "concreteType": "QuestionConnection",
            "name": "questions",
            "plural": false,
            "selections": [
              {
                "kind": "LinkedField",
                "alias": null,
                "args": null,
                "concreteType": "QuestionEdge",
                "name": "edges",
                "plural": true,
                "selections": [
                  {
                    "kind": "LinkedField",
                    "alias": null,
                    "args": null,
                    "concreteType": "Question",
                    "name": "node",
                    "plural": false,
                    "selections": [
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "id",
                        "storageKey": null
                      },
                      {
                        "kind": "ScalarField",
                        "alias": null,
                        "args": null,
                        "name": "questionText",
                        "storageKey": null
                      }
                    ],
                    "storageKey": null
                  }
                ],
                "storageKey": null
              }
            ],
            "storageKey": "questions{\"first\":10}"
          },
          {
            "kind": "LinkedField",
            "alias": null,
            "args": null,
            "concreteType": "UserNode",
            "name": "user",
            "plural": false,
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "username",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "email",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "id",
                "storageKey": null
              }
            ],
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedHandle",
        "alias": null,
        "args": null,
        "handle": "viewer",
        "name": "viewer",
        "key": "",
        "filters": null
      }
    ]
  },
  "text": "query rootViewerQuery {\n  viewer {\n    ...Account_viewer\n    ...Polls_viewer\n    user {\n      ...UserDropDown_user\n      id\n    }\n    id\n  }\n}\n\nfragment Account_viewer on Viewer {\n  id\n}\n\nfragment Polls_viewer on Viewer {\n  questions(first: 10) {\n    edges {\n      node {\n        id\n        ...Polls_question\n      }\n    }\n  }\n}\n\nfragment UserDropDown_user on UserNode {\n  username\n  email\n}\n\nfragment Polls_question on Question {\n  id\n  questionText\n}\n"
};

module.exports = batch;
